package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/theomorin/dbpilot/internal/detect"
)

// Generate builds a BackupConfig from the selected instances using sensible defaults.
// agePublicKey is embedded in each job's credentials when non-empty.
func Generate(instances []detect.DetectedInstance, agePublicKey string, dest DestinationConfig, s3AccessKey, s3SecretKey string) BackupConfig {
	cfg := BackupConfig{
		Global: GlobalConfig{
			VerifyRestore: false,
			VerifyTTL:     "30m",
		},
	}

	for _, inst := range instances {
		job := JobConfig{
			Name:      inst.Namespace + "-" + jobName(inst),
			DBVersion: inst.EngineVersion,
			Driver:    string(inst.Engine),
			Tool:      "wal-g",
			Encrypt:   true,
			Schedule:  "0 2 * * *", // daily at 02:00
			Retention: "7d",
			Environment: EnvironmentConfig{
				Type:      string(inst.Environment),
				Namespace: inst.Namespace,
			},
			Destinations: []DestinationConfig{
				{
					Name:        "primary",
					Type:        dest.Type,
					Bucket:      dest.Bucket,
					Endpoint:    dest.Endpoint,
					Region:      dest.Region,
					Prefix:      fmt.Sprintf("%s/%s", inst.Namespace, jobName(inst)),
					S3AccessKey: SecretRef{From: s3AccessKey},
					S3SecretKey: SecretRef{From: s3SecretKey},
				},
			},
			Credentials: CredentialsConfig{
				DBPassword:   SecretRef{From: fmt.Sprintf("k8s-secret://%s/dbpilot-credentials#db_password", inst.Namespace)},
				DBHost:       jobName(inst),
				AgePublicKey: agePublicKey,
			},
		}
		cfg.Jobs = append(cfg.Jobs, job)
	}

	return cfg
}

// ConfigDir returns ~/.config/dbpilot, creating it if needed.
func ConfigDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home dir: %w", err)
	}
	dir := filepath.Join(home, ".config", "dbpilot")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("creating config dir: %w", err)
	}
	return dir, nil
}

// NamedPath returns ~/.config/dbpilot/<name>.yaml, creating the directory if needed.
func NamedPath(name string) (string, error) {
	dir, err := ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, name+".yaml"), nil
}

// DefaultPath returns ~/.config/dbpilot/backup.yaml, kept for backward compatibility.
func DefaultPath() (string, error) {
	return NamedPath("backup")
}

// Write serializes cfg to path. Errors if the file already exists unless force is true.
func Write(cfg BackupConfig, path string, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists — use --force to overwrite", path)
		}
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshaling yaml: %w", err)
	}

	header := "# Generated by dbpilot — edit before use.\n" +
		"# Secrets must reference your secret backend, never be written in plain text.\n\n"

	return os.WriteFile(path, append([]byte(header), data...), 0644)
}

// jobName builds a stable, readable job name from the instance.
func jobName(inst detect.DetectedInstance) string {
	// Use pod name but strip the random suffix for Deployments (last two segments).
	// StatefulSets keep their ordinal (e.g. postgres-0) which is meaningful.
	parts := strings.Split(inst.PodName, "-")
	if len(parts) > 2 {
		// Heuristic: if last part is purely numeric it's a StatefulSet ordinal — keep it.
		last := parts[len(parts)-1]
		isOrdinal := true
		for _, c := range last {
			if c < '0' || c > '9' {
				isOrdinal = false
				break
			}
		}
		if !isOrdinal {
			// Strip last two random segments (replicaset hash + pod hash)
			parts = parts[:len(parts)-2]
		}
	}
	return strings.Join(parts, "-")
}
